name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vue-new:${{ github.sha }}

      - name: Update deployment.yaml 
        run: |
          sed -i 's|image: ${{ secrets.howon }}/vue-new:.*|image: ${{ secrets.howon }}/vue-new:${{ github.sha }}|' deployment.yaml
          cat deployment.yaml  

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ secrets.GITUSERNAME }}"
          git config --local user.email "${{ secrets.GITEMAIL }}"
          git config --local user.password "${{ secrets.GITPW }}"
          git add deployment.yaml
          git commit -m "[skip ci] Update image tag to ${{ github.sha }}"
          git push

    
